export default {
    SplashScreen: "SplashScreen",

    // Module1
    Connect: "Connect",
    ForgotPassword: "ForgotPassword",
    Home: "Home",
    MapSelection: "MapSelection",
    OTP: "OTP.tsx",
    SignIn: "SignIn",
    SignUp: "SignUp",
    Splash: "Splash",
    MorePage: "More",
    Cnic_page_1: 'Cnic_page_1',
    Cnic_page_2: 'Cnic_page_2',
    BiometricVerification: "BiometricVerification",
    BiometricSuccess: "BiometricSuccess",
    LanguageSelect: "LanguageSelect",

    Sidebar: "Sidebar",
    //specific to Internet
    NoInternet: "NoInternet",

    //Specific to Location
    LocationPermission: "LocationPermission",
    //Specific After logging in::
    MainTabNavigation: "MainTabNavigation",
    HomeScreen: "Home",
    HomeScreenMainStack: "HomeScreenMainStack",

    ELoanMainStack: "ELoanMainStack",
    ELoan: "E-Loan",
    EloanOTP: "E-LoanOTP",
    EloanPreviousLoan: "EloanPreviousLoan",
    EloanIDVerify: "EloanIDVerify",
    EloanLandVerify: "EloanLandVerify",
    EloanCurrentLoan: "EloanCurrentLoan",
    EloanSelectedLoan: "EloanSelectedLoan",
    ELoanNewLoan: "ELoanNewLoan",
    ELoanSetAside: "ELoanSetAside",
    ELoanSuccessScr: "ELoanSuccessScr",
    ELoanNewBank: "ELoanNewBank",
    EloanHBL: "EloanHBL",
    EloanMeezan: "EloanMeezan",
    EloanBOP: "EloanBOP",
    EloanZTBL: "EloanZTBL",
    ELoanFaisal: "ELoanFaisal",
    ELoanWoanScreen2: "ELoanWoanScreen2",
    ELoanPending: "ELoanPending",

    EWarehouseMainStack: "EWarehouseMainStack",
    EWarehouse: "EWarehouse",
    EWarehouseHomeScreen: "EWarehouseHomeScreen",
    EWarehouseRental: "EWarehouseRental",
    ESiloRental: "ESiloRental",
    EWarehouseNewSpaceCropSelect: "EWarehouseNewSpaceCropSelect",
    EWarehouseNewSpaceWarehouseSelect: "EWarehouseNewSpaceWarehouseSelect",
    EWarehouseNewSpaceConfirmWarehouse: "EWarehouseNewSpaceConfirmWarehouse",
    EWarehousePreviousWarehouses: "EWarehousePreviousWarehouses",
    EWarehousePreviousWarehouseDetails: "EWarehousePreviousWarehouseDetails",
    FoodSurveillanceSelectWarehouse: "FoodSurveillanceSelectWarehouse",
    FoodSurveillanceWarehouse: "FoodSurveillanceWarehouse",
    FoodSurveillanceItem: "FoodSurveillanceItem",


    EVendorsMainStack: "EVendorsMainStack",
    EVendors: "EVendors",
    EVendorsDetails: "EVendorsDetails",

    EInventory: "E-Inventory",
    EMarket: "E-Market",
    EMarketMainStack: "EMarketMainStack",

    //specific to each product
    ProductScr: "Product",

    EInventoryMainStack: "EInventoryMainStack",
    Inventory: "Inventory",
    PurchaseHistory: "PurchaseHistory",
    Sales: "Sales",
    Suppliers: "Suppliers",
    InventoryMonitoring: "InvetoryMonitoring",
    EInventoryReminder: "EInventoryReminder",
    EInventoryAddNew: "EInventoryAddNew",
    EInventoryAddNewGroup: "EInventoryAddNewGroup",
    ChangeLanguage: "ChangeLang",
    EInventoryManageGroup: "EInventoryManageGroup",
    EInventoryDetails: 'EInventoryDetails',


    EInventorySupplier: 'EInventorySupplier',
    EInventorySuppliersList: 'EInventorySuppliersList',
    EInventoryAddSuppliers: 'EInventoryAddSuppliers',
    EInventorySupplierReports: 'EInventorySupplierReports',


    //For E-Mandi
    EMandi: 'E-Mandi',
    EMandiMainStack: 'EMandiMainStack',
    EMandiHomeScreen: 'EMandiHomeScreen',
    RequestForAuction: 'RequestForAuction',
    MyAuctions: 'MyAuctions',
    MyAuctionDetail: 'MyAuctionDetail',
    Auctions: 'Auctions',
    AuctionHistory: 'AuctionHistory',
    AuctionHistoryDetails: 'AuctionHistoryDetails',
    AuctionSubmissionSuccess: 'AuctionSubmissionSuccess',
    LiveAuctions: 'LiveAuctions',
    AuctionHistoryPaymentMethod: 'AuctionHistoryPaymentMethod',
    AuctionDetails: 'AuctionDetails',
    MarketDept: 'MarketDept',
    Profile: 'Profile',


    ETransportStack: "ETransportStack",
    ETransportAddDetails: "ETransportAddDetails",
    ETransportAir: "ETransportAir",
    ETransportAnalytics: "ETransportAnalytics",
    ETransportDeliveryHistory: "ETransportDeliveryHistory",
    ETransportNewTransport: "ETransportNewTransport",
    ETransportSelectVehicleType: "ETransportSelectVehicleType",
    ETransportShip: "ETransportShip",
    ETransportTruck: "ETransportTruck",
    ETransportMain: "ETransportMain",
    SelectLangSideBar: "SelectLangSideBar",
    MyProfileMainStack: "MyProfileMainStack",
    MyProfile: "MyProfile",
    ProfileChangeLanguage: "ProfileChangeLanguage",
    BankRecieving: "BankRecieving",
    RaastRecieving: "RaastRecieving",
    Recieving: "Recieving",

    EMunshiMainStack: "EMunshiMainStack",
    EMunshi: "EMunshi",
    EMunshiItemName: "EMunshiItemName",
    EMunshiCashFlow: "EMunshiCashFlow",
    EMunshiFarmName: "EMunshiFarmName",
    EMunshiWarehouseInfo: "EMunshiWarehouseInfo",
    FoodSafetyAndSecurity: "FoodSafetyAndSecurity",
    EmunshiLineOfCredit: "EmunshiLineOfCredit",
    EmunshiDisputeTransaction: "EmunshiDisputeTransaction",
    EmunshiTransactionDetail: "EmunshiTransactionDetail",


    EOrderHistory: "EOrderHistory",
    EOrderMainStack: "EOrderMainStack",
    EOrderManager: "EOrderManager",
    EOrderPlaceOrder: "EOrderPlaceOrder",
    EOrderTransaction: "EOrderTransaction",
    EOrderCheckout: "EOrderCheckout",
    EOrderPaymentMethod: "EOrderPaymentMethod",
    OTPSignUp: "OTPSignUp",
    RaastPaymentScreen: "RaastPaymentScreen",
    RaastConfirmPayment: "RaastConfirmPayment",
    PaymentSuccess: "PaymentSuccess",
    AllOTP: "AllOTP",
    LineOfCreditPay: "LineOfCreditPay",
    EVendorViewTranscations: "EVendorViewTranscations",

    PlantDoctorMainStack: "PlantDoctorMainStack",
    AddCrop: "AddCrop",
    Diagnosis: "Diagnosis",
    DosageCalculator: "DosageCalculator",
    FertilizerCalculator: "FertilizerCalculator",
    HealCropImageCapture: "HealCropImageCapture",
    CultivationTips: "CultivationTips",
    Pest: "Pest",
    Prevent: "Prevent",
    PestAndDiseasesAlert: "PestAndDiseasesAlert",
    PlantDrCommunity: "PlantDrCommunity",
    DrPostDetail: "DrPostDetail",
    Treatment: "Treatment",
    TreatmentProductDescription: "TreatmentProductDescription",
    TreatNow: "TreatNow",
    PlantDoctor: "PlantDoctor",
    PestsAndDiseases: "PestsAndDiseases",
    FertilizerCombinations: "FertilizerCombinations",
    MOPTSP: "MopTspUrea",
    SeedlingStage: "SeedlingStage",
    FertilizationChemical: "FertilizationChemical",
    BasalFertilization: "BasalFertilization",
    Fetch1: "Fetch1",
    NewHomeMainStack: "NewHomeMainStack",
    NewHomeScreen: "NewHomeScreen",
    DashboardScreen: "DashboardScreen",
    DashBoardNew: "DashBoardNew",
    ELoanNew: "ELoanNew",
    EENewLoan: "EENewLoan",
    ELoanRequestNewLoan: "ELoanRequestNewLoan",
    ELoanRequest2: "ELoanRequest2",
    ELoanRequest3: "ELoanRequest3",
    ELoanSuccess: "ELoanSuccess",
    ELoanHistory: "ELoanHistory",
    ELoanEach: "ELoanEach",
    ELoanPendingScreen: "ELoanPendingScreen",
    ELoanCurrentLoan: "ELoanCurrentLoan",
    ELoanMadadgar: "ELoanMadadgar",
    ELoanMadadgarS2: "ELoanMadadgarS2",
    ELoanMadadgarS3: "ELoanMadadgarS3",
    ELoanMadadgarSuccess: "ELoanMadadgarSuccess",

    // Minority Loan screens
    ELoanMinority: "ELoanMinority",
    ELoanMinorityS2: "ELoanMinorityS2",
    ELoanMinorityS3: "ELoanMinorityS3",
    ELoanMinoritySuccess: "ELoanMinoritySuccess",

    // Women Loan screens
    ELoanWomen: "ELoanWomen",
    ELoanWomenS2: "ELoanWomenS2",
    ELoanWomenS3: "ELoanWomenS3",
    ELoanWomenSuccess: "ELoanWomenSuccess",

    // Micro Finance screens
    ELoanMicroF: "ELoanMicroF",
    ELoanMicroFS2: "ELoanMicroFS2",
    ELoanMicroFS3: "ELoanMicroFS3",
    ELoanMicroFSuccess: "ELoanMicroFSuccess",

    // Settlements screens
    SettlementsMainStack: 'SettlementsMainStack',
    SettlementsScr: 'SettlementsScr',
    SummaryOfSpendingsScr: 'SummaryOfSpendingsScr',
    RaastPaymentScr: 'RaastPaymentScr',

    EWarehouseSuccess: 'EWarehouseSuccess',
    ESiloRental2: "ESiloRental2",
    EColdStorageRental: 'EColdStorageRental',
    ExistingRentals: 'ExistingRentals',
    RentalDetails: 'RentalDetails',
    ELoanNewLand: 'ELoanNewLand',
    EAdviser: 'EAdviser',
    AgriServices: 'AgriServices',
    CropAdvisor: 'CropAdvisor',
    ZoneDetails: 'ZoneDetails',
    FertilizerAdvisor: 'FertilizerAdvisor',
    EAdviserMainStack: 'EAdviserMainStack',
    FertilizerAdvisorSelectedCrop: 'FertilizerAdvisorSelectedCrop',
    ApplicationInstructions: 'ApplicationInstructions',
    FertilizationSchedule: 'FertilizationSchedule',
    PricingAdvisor: 'PricingAdvisor',
    ProfitMaximisation: 'ProfitMaximisation',
    ProductPricing: 'ProductPricing',
    YieldTracker: 'YieldTracker',
    CropYield: 'CropYield',
    Diagnostics: 'Diagnostics',
    CropDiagnostics: 'CropDiagnostics',
    SoilTesting: 'SoilTesting',
    RequestSoilTesting: 'RequestSoilTesting',
    SoilTestingReport: 'SoilTestingReport',
    
}